language: go
go:
 - "1.10"

# Don't email me the results of the test runs.
notifications:
  email: false

services:
  - rabbitmq

git:
  depth: 1

script:
 - goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")
 - go test -v ./... | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''

os: linux

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get golang.org/x/tools/cmd/goimports

install:
  - dep ensure