language: go
go:
 - "1.10"

# Don't email me the results of the test runs.
notifications:
  email: false

services:
  - rabbitmq

git:
  depth: 1

script:
 - diff -u <(echo -n) <(goimports -l ./)
 - go test -v ./...

os: linux

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get golang.org/x/tools/cmd/goimports

install:
  - dep ensure