engine:
  keypath: .it-chain/
  mode: solo
  amqp: rabbitmq://guest:guest@localhost:5672/
  bootstrapnodeaddress: 127.0.0.1:5555
txpool:
  timeoutms: 1000
  maxtransactionbyte: 1024
consensus:
  batchtime: 3
  maxtransactions: 100
blockchain:
  genesisconfpath: ./gensis.conf
peer:
  leaderelection: RAFT
icode:
  repositorypath: empty
  icodesavepath: ./.tmp
grpcgateway:
  address: 127.0.0.1
  port: "13579"
apigateway:
  address: 127.0.0.1
  port: "4444"
