engine:
  logpath: log/it-chain.log
  keypath: .it-chain/
  mode: pbft
  amqp: amqp://guest:guest@localhost:5672/
  bootstrapnodeaddress: 
txpool:
  timeoutms: 1000
  maxtransactionbyte: 1024
consensus:
  batchtime: 3
  maxtransactions: 100
blockchain:
  genesisconfpath: ./Genesis.conf
peer:
  leaderelection: RAFT
icode:
  repositorypath: empty
grpcgateway:
  address: 172.18.1.0
  port: 5000
apigateway:
  address: 172.18.1.0
  port: 4000
